title: AI-PITCH
email: contact@aipitch.eu
description: AI-Powered Innovative Toolkit for Cybersecurity Hubs, advancing practical and trustworthy AI for phishing threat detection and response.
url: https://aipitch.eu
baseurl: ""
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
