title: AI-PITCH
email: contact@aipitch.eu
description: AI-Powered Innovative Toolkit for Cybersecurity Hubs, providing AI-powered tools for national and enterprise cyberdefence teams.
url: https://aipitch.eu
baseurl: ""
markdown: kramdown
permalink: pretty
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: publications
    values:
      layout: publication
collections:
  projects:
    output: true
    permalink: /projects/:name/
  publications:
    output: true
    permalink: /publications/:name/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
